<a href="https://colab.research.google.com/github/proinsiasR/Richardson_Extrapolation_ReciprocalSquares/blob/main/Richardson_Extrapolation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
s_15 = np.pi**2/6
# Value of the sum of square reciprocals from 1 to inf..... 
#  so sum i=1 to inf of 1/(n^2)
# It's good for at least 15 decimal places using python for that value
s_15

1.6449340668482264

In [ ]:
cols = int(50)

# SN = 0
# for i in range(cols):
#   SN += 1/((i+1)**2)

SN = np.zeros(150)
for i in range(150):
  SN[i] = 1/((i+1)**2) + SN[i-1]

SN

array([1.        , 1.25      , 1.36111111, 1.42361111, 1.46361111,
       1.49138889, 1.51179705, 1.52742205, 1.53976773, 1.54976773,
       1.55803219, 1.56497664, 1.5708938 , 1.57599584, 1.58044028,
       1.58434653, 1.58780674, 1.59089316, 1.59366324, 1.59616324,
       1.59843082, 1.60049693, 1.60238729, 1.6041234 , 1.6057234 ,
       1.60720269, 1.60857444, 1.60984995, 1.61103901, 1.61215012,
       1.6131907 , 1.61416726, 1.61508554, 1.61595059, 1.61676691,
       1.61753852, 1.61826898, 1.6189615 , 1.61961896, 1.62024396,
       1.62083885, 1.62140574, 1.62194657, 1.6224631 , 1.62295693,
       1.62342952, 1.62388221, 1.62431624, 1.62473273, 1.62513273,
       1.6255172 , 1.62588702, 1.62624302, 1.62658596, 1.62691654,
       1.62723541, 1.6275432 , 1.62784047, 1.62812774, 1.62840552,
       1.62867426, 1.62893441, 1.62918636, 1.6294305 , 1.62966719,
       1.62989676, 1.63011952, 1.63033579, 1.63054583, 1.63074991,
       1.63094828, 1.63114118, 1.63132883, 1.63151145, 1.63168

In [ ]:
R1 = np.zeros(cols)
for i in range(cols-1):
  R1[i] = SN[i+1]*(i+1) - i*SN[i]
R1

array([1.25      , 1.47222222, 1.54861111, 1.58361111, 1.6025    ,
       1.61383787, 1.62117205, 1.62618748, 1.62976773, 1.63241236,
       1.63442108, 1.63598256, 1.63722033, 1.63821806, 1.63903403,
       1.63970986, 1.64027588, 1.64075466, 1.64116324, 1.64151472,
       1.64181925, 1.64208484, 1.64231785, 1.6425234 , 1.64270565,
       1.64286799, 1.64301321, 1.64314364, 1.64326123, 1.6433676 ,
       1.64346414, 1.64355202, 1.64363225, 1.64370569, 1.64377309,
       1.64383509, 1.64389225, 1.64394506, 1.64399396, 1.64403932,
       1.64408148, 1.64412072, 1.64415732, 1.6441915 , 1.64422347,
       1.64425342, 1.64428152, 1.64430791, 1.64433273, 0.        ])

In [ ]:
R2 = np.zeros(cols)
for i in range(cols-2):
  R2[i] = 0.5*(SN[i+2]*(i+2)**2 - SN[i+1]*2*(i+1)**2 + SN[i]*i**2)

R2
R2[25]

1.6448284948810965

In [ ]:
R8 = np.zeros(cols)
for i in range(cols-8):
  R8[i] = (1/(8*7*6*5*4*3*2*1))*(SN[i+8]*(i+8)**8 - 8*SN[i+7]*(i+7)**8 + 28*SN[i+6]*(i+6)**8 - 56*SN[i+5]*(i+5)**8 + 70*SN[i+4]*(i+4)**8 - 56*SN[i+3]*(i+3)**8 + 28*SN[i+2]*(i+2)**8 - 8*SN[i+1]*(i+1)**8 + SN[i]*i**8)

R8[::5]

array([1.64491969, 1.64493406, 1.64493407, 1.64493406, 1.644934  ,
       1.64493392, 1.64493391, 1.644936  , 1.64493796, 0.        ])